import Head from 'next/head';
import styles from '../styles/Home.module.css';

import Banner from '../components/banner';
import Card from '../components/card';

export default function Home() {
  const handleOnButtonClick = () => {
    console.log('pressed');
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Shops</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText='View stores nearby'
          handleOnClick={handleOnButtonClick}
        />
        <Card
          name='DarkHorse Coffee'
          imgUrl='/static/test.jpeg'
          href='/coffee-store/darkhorse-coffee'
        />
      </main>
    </div>
  );
}
